![Google Drive Image](https://drive.google.com/uc?export=view&id=1zLi1EkeMV8U5nADzIndtPJj041F51g0y)

<h1><center>Laboratorio 1: Numpy 📷</center></h1>

<center><strong>Introducción, Entorno de Desarrollo y Manejo de Arreglos con Numpy</strong></center>

### Cuerpo Docente:

- Profesor de Catedra: [Pablo Badilla](https://github.com/pbadillatorrealba/)
- Profesor Practico  : [Gabriel Iturra-Bocaz](https://giturra.cl/).

### Reglas:

- **Grupos de 2 personas**: Daniela Mancilla y Francisca Quijada
- **Ausentes** deberán realizar la actividad solos.
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Pueden usar cualquer matrial del curso que estimen conveniente, si utiliza material extra debe citarlo.


### Temas a tratar:

- `Numpy` para manejo de datos en arreglos.

### Objetivos principales del laboratorio

- Comprender y aprovechar las ventajas que nos ofrece la Liberia  `numpy` con respecto a trabajar con las funciones de `Python` de forma nativa.
- Verificar que el uso indiscriminado de `for` puede afectar en la eficiencia en al procesar datos masivos.

El objetivo principal de este laboratorio es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `numpy`, las cuales son mucho más eficientes que los iteradores nativos sobre arreglos.

## Problema 1: Creación de Arreglos

1. Transforme la lista de python `array_a` dispuesta en la celda de mas abajo en un arreglo Numpy. Agregue su código y muestre sus resultados.

In [ ]:
# Transforme una lista de Python al formato Numpy Array:

# A continuación, se define la lista lista_a
lista_a = [[5, 10, 9], [2, 7, 8], [6, 3, 1], [7, 7, 9], [0, 8, 4]]

# A partir de la lista anterior, inicialice un arreglo llamado array_a

In [ ]:
import numpy as np
array_a=np.array(lista_a)
array_a

array([[ 5, 10,  9],
       [ 2,  7,  8],
       [ 6,  3,  1],
       [ 7,  7,  9],
       [ 0,  8,  4]])

> **Pregunta ❓**Qué sucederá al ejecutar la siguiente celda?


In [ ]:
array_b = np.array([[5, 10, 9], [2, 7, 8], [2]])
array_b

<ipython-input-6-dff8445882cf>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_b = np.array([[5, 10, 9], [2, 7, 8], [2]])


array([list([5, 10, 9]), list([2, 7, 8]), list([2])], dtype=object)

```
Python no lo interpreta como una matriz y genera una lista (un
vector) de listas. Esto ocurre porque el último elemento tiene dimensión 1,
mientras que los dos primeros elementos tienen dimensión 3.
```

2. Cree arreglos de numpy conformados de unos, ceros y con numeros aleatorios. Considere la creación de los arreglos con las siguiente dimensión: `(2, 5)`.

In [ ]:
# Arreglos conformados con unos
array_unos =np.ones((2,5))

# Arreglos conformados por ceros
array_ceros =np.zeros((2,5))


# Arreglos Aleatorios
array_aleatorios =np.random.random((2,5))

#array_unos
#array_ceros
#array_aleatorios

3.- El número de dimensiones del arreglo.

In [ ]:
array_unos.ndim
array_ceros.ndim
array_aleatorios.ndim

2

4.- El número de elementos del arreglo en cada dimensión.

In [ ]:
array_unos.shape
array_ceros.shape
array_aleatorios.shape

(2, 5)

5.- El número total de elementos que contiene el arreglo.

In [ ]:
array_unos.size
array_ceros.size
array_aleatorios.size

10

6.- El tipo de datos que contiene el arreglo.

In [ ]:
array_unos.dtype
array_ceros.dtype
array_aleatorios.dtype

dtype('float64')

## Problema 2: Operaciones con Numpy

1. A cada elemento del arreglo `array_a` sume `3` .

In [ ]:
array_a+3

array([[ 8, 13, 12],
       [ 5, 10, 11],
       [ 9,  6,  4],
       [10, 10, 12],
       [ 3, 11,  7]])

2. Ahora, genere un arreglo `valores_1 = [1, 2, 3]` el cuál tiene una sola dimensión con 3 elementos, sumelo a `array_a` y guardelo en la variable `resultado_1`. ¿Cómo se aplica la operación en este caso?

In [ ]:
valores_1 =np.array([1,2,3])
resultado_1=array_a+valores_1

array([[ 6, 12, 12],
       [ 3,  9, 11],
       [ 7,  5,  4],
       [ 8,  9, 12],
       [ 1, 10,  7]])

In [ ]:
array_a

array([[ 5, 10,  9],
       [ 2,  7,  8],
       [ 6,  3,  1],
       [ 7,  7,  9],
       [ 0,  8,  4]])

```
La operación consiste en sumar los elementos del arreglo valores_1 a las columnas del arreglo array_a.
Es decir, suma 1 a la primera columna, suma 2 a la segunda columna, y suma 3 a la tercera columna.
```

3. Sume a `array_a` la siguiente lista `valores_2 = [[100],[3],[10],[22],[30]]` de dimension (5,1). ¿Cómo se aplica la operación en este caso?

In [ ]:
valores_2 =np.array([[100],[3],[10],[22],[30]])
resultado_2=array_a+valores_2
resultado_2

array([[105, 110, 109],
       [  5,  10,  11],
       [ 16,  13,  11],
       [ 29,  29,  31],
       [ 30,  38,  34]])

```
La operación consiste en sumar los elementos del arreglo valores_2 a las filas del arreglo array_a.
Es decir, suma 100 a la fila 1, suma 3 a la fila 2, y así sucesivamente.
```


4. Intente sumar a `array_a` la siguiente lista `valores_3 = [100, 3, 10 , 22 , 30]` de dimension (5). ¿Qué sucede en este caso y por qué?

In [ ]:
valores_3 = np.array([100, 3, 10 , 22 , 30])
resultado_3=array_a+valores_3
resultado_3

ValueError: ignored

```
Entrega un error, pues intenta sumar 5 valores a las columnas que son 3.
```

5. Aplique la ecuación definida mas abajo a cada uno de los valores del arreglo `array_a` :

    - $$ tan(x) = \dfrac{sin(x)}{cos(x)} $$

**Nota:** No utilice directamente la función `tan` de numpy.


In [ ]:
tan=np.sin(array_a)/np.cos(array_a)
tan

array([[-3.38051501,  0.64836083, -0.45231566],
       [-2.18503986,  0.87144798, -6.79971146],
       [-0.29100619, -0.14254654,  1.55740772],
       [ 0.87144798,  0.87144798, -0.45231566],
       [ 0.        , -6.79971146,  1.15782128]])

6. Aplique la ecuación definida mas abajo a cada uno de los valores del arreglo `array_a` [0.1 puntos]:

- $$ sigmoide(x) = \dfrac{1}{1 + e^{-x}} $$


In [ ]:
sigmoid =1/(1+np.exp(-array_a))
sigmoid

array([[0.99330715, 0.9999546 , 0.99987661],
       [0.88079708, 0.99908895, 0.99966465],
       [0.99752738, 0.95257413, 0.73105858],
       [0.99908895, 0.99908895, 0.99987661],
       [0.5       , 0.99966465, 0.98201379]])

7. Encuentre los valores máximo y el mínimo del arreglo `array_a`

In [ ]:
maximo=np.max(array_a)
minimo=np.min(array_a)
maximo,minimo

(10, 0)

## Problema 3: Indexadores

1. Obtenga la segunda fila del arreglo `array_a`

In [ ]:
array_a[1]

array([2, 7, 8])

2. Obtenga las filas 1, 2 y 3 del arreglo `array_a`

In [ ]:
array_a[0:3]

array([[ 5, 10,  9],
       [ 2,  7,  8],
       [ 6,  3,  1]])

3. Obtenga todas las filas a partir de la fila 3 (incluyendola).

In [ ]:
array_a[2:]

array([[6, 3, 1],
       [7, 7, 9],
       [0, 8, 4]])

4. Obtenga las filas 2 y 4

In [ ]:
array_a[[1,3]]

array([[2, 7, 8],
       [7, 7, 9]])

5. Repita el ejercicio anterior, pero ahora usando valores booleanos (`True`, `False`)

In [ ]:
array_a[[False, True, False, True, False]]

array([[2, 7, 8],
       [7, 7, 9]])

6. Obtenga todos los valores de la segunda columna

In [ ]:
array_a[:,1]

array([10,  7,  3,  7,  8])

7. Obtenga de la segunda y tercera fila, la primera y última columna. [0.2 puntos]

In [ ]:
array_a[1:3,[0,2]]

array([[2, 8],
       [6, 1]])

## Problema 4: Consultas

En esta sección le solicitamos seleccionar ciertos datos el arreglo original `array_a` a través de consultas.

Es muy recomendable que antes de seleccionar los datos, impriman el arreglo que contiene los valores booleanos con los cuales seleccionarán los datos.

1. Obtenga todos los valores iguales a 7 en el `array_a`.

In [ ]:
array_a == 7

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [ True,  True, False],
       [False, False, False]])

In [ ]:
array_a[array_a == 7]

array([7, 7, 7])

2. Obtenga todos los valores mayores a 7

In [ ]:
array_a > 7

array([[False,  True,  True],
       [False, False,  True],
       [False, False, False],
       [False, False,  True],
       [False,  True, False]])

In [ ]:
array_a[array_a > 7]

array([10,  9,  8,  9,  8])

3. Obtenga todos los números impares

In [ ]:
array_a % 2==1

array([[ True, False,  True],
       [False,  True, False],
       [False,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [ ]:
array_a[array_a % 2==1]

array([5, 9, 7, 3, 1, 7, 7, 9])

4. Obtenga todos los valores abarcados entre 6 y 8 incluyendo ambos.

In [ ]:
condition_1 = array_a >= 6
condition_2 = array_a <= 8
array_a[np.logical_and(condition_1,condition_2)]

array([7, 8, 6, 7, 7, 8])

5. Fije el valor 0 para todos los valores superiores a 5 en el `array_a`.

In [ ]:
array_a*(array_a<=5)

array([[5, 0, 0],
       [2, 0, 0],
       [0, 3, 1],
       [0, 0, 0],
       [0, 0, 4]])

## Problema 5: Operaciones sobre las dimensiones (Propuesto)

En este item se le solicita ejecutar acciones sobre las distintas dimensiones que componen el arreglo.

Recordatorio: utilizar el parámetro `axis` para indicar la dimensión en donde se desea ejecutar la acción.

1. Sume todos los valores de las filas.

In [ ]:
array_a.sum(axis=1)

array([24, 17, 10, 23, 12])

2. Sume todos los valores de las columnas.

In [ ]:
array_a.sum(axis=0)

array([20, 35, 31])

3. Encuentre el máximo de cada columna

In [ ]:
array_a.max(axis=0)

array([ 7, 10,  9])

4. Encuentre el mínimo de cada fila

In [ ]:
array_a.min(axis=1)

array([5, 2, 1, 7, 0])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=87110296-876e-426f-b91d-aaf681223468' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>